import Head from "next/head";
import NavComponent from "../components/NavComponent";
import HeaderComponent from "../components/HeaderComponents";
import ContactUsComponent from "../components/ContactUsComponent";
import MakeWebsiteComponent from "../components/MakeWebsiteComponent";
import FooterComponent from "../components/FooterComponent";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavComponent onIndex="true" />
      <HeaderComponent name="get a quote" />

      <ContactUsComponent />
      <MakeWebsiteComponent />
      <FooterComponent />
    </div>
  );
}
