import Head from "next/head";
import NavComponent from "../components/NavComponent";
import FooterComponent from "../components/FooterComponent";
import MakeWebsiteComponent from "../components/MakeWebsiteComponent";
import HeadSeactionComponent from "../components/HeadSeactionComponent";
import HowWeCanHelpComponent from "../components/HowWeCanHelpComponent";
import CardComponent from "../components/CardComponents";
import HelpProcessComponent from "../components/HelpProcessComponent";
import ContactUsComponent from "../components/ContactUsComponent";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavComponent onIndex="true" />
      <HeadSeactionComponent />
      <HowWeCanHelpComponent />
      <CardComponent />
      <HelpProcessComponent />
      <ContactUsComponent />

      <MakeWebsiteComponent />
      <FooterComponent />
    </div>
  );
}
