import Head from "next/head";
import NavComponent from "../components/NavComponent";
import FooterComponent from "../components/FooterComponent";
import MakeWebsiteComponent from "../components/MakeWebsiteComponent";
import HeadSeactionComponent from "../components/HeadSeactionComponent";
import HowWeCanHelpComponent from "../components/HowWeCanHelpComponent";
import CardComponent from "../components/CardComponents";
import HelpProcessComponent from "../components/HelpProcessComponent";
import ContactUsComponent from "../components/ContactUsComponent";
import AwesomeServiceComponent from "../components/AwesomeServiceComponent";
import OurLatestProject from "../components/OurLatestProject";
import Testimonials from "../components/Testimonials";
import { useEffect, useState } from "react";

export default function Home() {
  const [showModal, setShowModal] = useState("");

  useEffect(() => {
    setShowModal(true);
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavComponent showModal={showModal} setShowModal={setShowModal} />
      <HeadSeactionComponent />
      <AwesomeServiceComponent title="Provide Awesome Service To You" />
      <HowWeCanHelpComponent />
      <CardComponent />
      <HelpProcessComponent />
      <Testimonials />
      <OurLatestProject />
      <ContactUsComponent />
      <MakeWebsiteComponent />
      <FooterComponent />
    </div>
  );
}
