import Head from "next/head";
import NavComponent from "../components/NavComponent";
import FooterComponent from "../components/FooterComponent";
import MakeWebsiteComponent from "../components/MakeWebsiteComponent";
import HeaderComponent from "../components/HeaderComponents";
import OurLatestProject from "../components/OurLatestProject";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavComponent />
      <HeaderComponent name="Our portfolio" />

      <OurLatestProject />

      <MakeWebsiteComponent />
      <FooterComponent />
    </div>
  );
}
